version: '3.8'

services:
  hadb:
    image: mariadb:latest
    container_name: home_assistant_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - hadb:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password  # Mot de passe de l'utilisateur root de mariadb
     - MYSQL_DATABASE=db  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=mysql  # Nom de l'utilisateur de la base de données créée
     - MYSQL_PASSWORD=password  # Mot de passe de l'utilisateur créé  

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home_assistant
    restart: always
    volumes:
    - config:/config
    links:
    - hadb
    environment:
     - MYSQL_DATABASE=db  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=mysql  # Nom de l'utilisateur de la base de données créée
     - MYSQL_PASSWORD=password # Mot de passe de l'utilisateur créé  

volumes:
  config:
  hadb:
